### ISSUE TITLE
Problem In UWP

### ISSUE THREAD

**Issue by ZCOREP** [bezzad/Downloader#101]
I tried to download files in UWP framework, 
this is my code : 
"

                var downloadOpt = new DownloadConfiguration()
                {
                    ChunkCount = 8, 
                    OnTheFlyDownload = true,  
                    ParallelDownload = true  
                };
                var file = await DownloadsFolder.CreateFileAsync("myfile.zip", CreationCollisionOption.GenerateUniqueName);
                var downloader = new DownloadService(downloadOpt);
                downloader.DownloadProgressChanged += OnDownloadProgressChanged;
                await downloader.DownloadFileTaskAsync(mylink, file.Path);

"

When it reaches 100% download, nothing happens and it stops at this line of code, no error no warning nothing !
         await downloader.DownloadFileTaskAsync(mylink, file.Path);

**Comment by bezzad** [comment]
Which version do you use and what is your URL?

**Comment by ZCOREP** [comment]
Version 2.3.6
Any URL

**Comment by ghost1372** [comment]
> Version 2.3.6
> Any URL 

I think you can't save files in UWP because of permissions, so you should use OpenFilePicker or FileFilePicker to specify the path to save the file.
Or you can give full access to your app, but in this case the store will reject your app

**Comment by ZCOREP** [comment]
{
var file = await DownloadsFolder.CreateFileAsync("myfile.zip", CreationCollisionOption.GenerateUniqueName);
file.path
It gives us the exact address
}
with this code

**Comment by bezzad** [comment]
This issue is related to your application not to the Downloader. because you can download it on the fly (on memory) instead of on disk. So the permission concept is for your application. You can give access to write data and give an address to Downloader which you can write on that.

**Comment by ghost1372** [comment]
> {
> var file = await DownloadsFolder.CreateFileAsync("myfile.zip", CreationCollisionOption.GenerateUniqueName);
> file.path
> }
> 
> It gives us the exact address
> 

You need **runFullTrust** google it and follow inatructures...

**Comment by ZCOREP** [comment]
no its not about the permission!  
BackgroundDownloader can download it!

**Comment by ZCOREP** [comment]
i used runFullTrust  but its not work

**Comment by ghost1372** [comment]
> i used runFullTrust  but its not work

Please upload a repro project

**Comment by ZCOREP** [comment]
[Downloader UWP.zip](https://github.com/bezzad/Downloader/files/9437452/Downloader.UWP.zip)

here my repo

**Comment by ghost1372** [comment]
> [Downloader UWP.zip](https://github.com/bezzad/Downloader/files/9437452/Downloader.UWP.zip)
> 
> here my repo

Tnx @ZCOREP 
First of all you need to use SaveFilePicker

```
var savePicker = new Windows.Storage.Pickers.FileSavePicker();
savePicker.SuggestedStartLocation =
Windows.Storage.Pickers.PickerLocationId.DocumentsLibrary;
// Dropdown of file types the user can save the file as
savePicker.FileTypeChoices.Add("Archive", new List<string>() { ".zip" });
// Default file name if the user does not type one in or select a file to replace
savePicker.SuggestedFileName = "myfile";


Windows.Storage.StorageFile file = await savePicker.PickSaveFileAsync();
if (file != null)
{
// Prevent updates to the remote version of the file until
// we finish making changes and call CompleteUpdatesAsync.
Windows.Storage.CachedFileManager.DeferUpdates(file);
// write to file
//await Windows.Storage.FileIO.WriteTextAsync(file, file.Name);


var downloader = new DownloadService();
downloader.DownloadProgressChanged += OnDownloadProgressChanged;
await downloader.DownloadFileTaskAsync(mylink, file.Path);


// Let Windows know that we're finished changing the file so
// the other app can update the remote version of the file.
// Completing updates may require Windows to ask for user input.
Windows.Storage.Provider.FileUpdateStatus status =
    await Windows.Storage.CachedFileManager.CompleteUpdatesAsync(file);
if (status == Windows.Storage.Provider.FileUpdateStatus.Complete)
{
    //this.textBlock.Text = "File " + file.Name + " was saved.";
}
else
{
    //this.textBlock.Text = "File " + file.Name + " couldn't be saved.";
}
}
else
{
//this.textBlock.Text = "Operation cancelled.";
}
```

Second, i tested with another url and everything worked fine as you can see in image progress status is working...

![image](https://user-images.githubusercontent.com/9213496/187020656-492b404c-fd10-4104-8ca5-27bd40c9687e.png)

So, The problem is with your URL.

@bezzad  you need to check/test this url, download will be terminated without any useful info.

`https://c2rsetup.officeapps.live.com/c2r/downloadVS.aspx?sku=community&channel=Release&version=VS2022&source=VSLandingPage&includeRecommended=true&cid=2030:9bf2104738684908988ca7dcd5dafed1`

**Comment by ZCOREP** [comment]
The problem is when it reaches 100%, not when it starts downloading

**Comment by ghost1372** [comment]
> The problem is when it reaches 100%, not when it starts downloading

When I test it, it crashes when i click on button

**Comment by ZCOREP** [comment]
test it with any link you want, it has the same problem

**Comment by bezzad** [comment]
@ZCOREP @ghost1372 I checked it with the last version 2.3.7 and I couldn't find any problem. I also download it without a VPN and it's no problem. But when I download it the Downloader v2.3.6 had a problem because that server couldn't support downloading in a specific range.
Please update your Downloader package to v2.3.7 and test it again.

**Comment by ZCOREP** [comment]
can you please send me your UWP repo ?

**Comment by ghost1372** [comment]
@bezzad 
v2.3.7

![Animation2](https://user-images.githubusercontent.com/9213496/187029896-20d7805a-4fb8-450e-8540-ef4f2b06a0f3.gif)

**Comment by ZCOREP** [comment]
Exactly , i'm talking about this

**Comment by ZCOREP** [comment]
> @bezzad v2.3.7
> 
> ![Animation2](https://user-images.githubusercontent.com/9213496/187029896-20d7805a-4fb8-450e-8540-ef4f2b06a0f3.gif) [ ![Animation2](https://user-images.githubusercontent.com/9213496/187029896-20d7805a-4fb8-450e-8540-ef4f2b06a0f3.gif) ](https://user-images.githubusercontent.com/9213496/187029896-20d7805a-4fb8-450e-8540-ef4f2b06a0f3.gif) [ ](https://user-images.githubusercontent.com/9213496/187029896-20d7805a-4fb8-450e-8540-ef4f2b06a0f3.gif)

Exactly , i'm talking about this

**Comment by ZCOREP** [comment]
Exactly , i'm talking about this

**Comment by bezzad** [comment]
> can you please send me your UWP repo ?

I used the Console application and it could be downloaded successfully.

**Comment by bezzad** [comment]
> can you please send me your UWP repo ?

I used the Console application and it could be downloaded successfully.

**Comment by bezzad** [comment]
I check your repository and don't worry I saw the problem. I work on that to fix it.

**Comment by bezzad** [comment]
I found the exception: ‍`Access to the path 'D:\TestDownload' is denied.`

When the Downloader run `System.IO.Directory.CreateDirectory(@"D:\TestDownload");`  

I search the issue and I found it because .Net Core `System.IO` commands do not work in the UWP sandbox and you must store files with `StorageFile` instead of the default `System.IO`. [Issue Reference](https://stackoverflow.com/questions/56111084/does-file-exists-not-work-inside-a-uwp-project)

Well, now what can you do to solve this issue?
At first, you suppose that the Downloader can't add a reference to the `StorageFile` library because it's an independent library and it can't use this library on other platforms. 
So you should get the download result as a stream and store it in the file by self commands instead of the Downloader. Such as [these codes](https://github.com/bezzad/Downloader#step-4c-download-in-memorystream):

```csharp
Stream destinationStream = await downloader.DownloadFileTaskAsync(url);
// your UWP codes to store destinationStream on local file
```

**Comment by ZCOREP** [comment]
how should i store destinationStream on local file ? 
can you  please send me full code?

**Comment by bezzad** [comment]
> how should i store destinationStream on local file ? can you please send me full code?

I added the below codes but I don't sure if this way is good in UWP or not. Just it is working.

```csharp
Windows.Storage.StorageFolder storageFolder = await StorageFolder.GetFolderFromPathAsync(mypath);
                Windows.Storage.StorageFile sampleFile = await storageFolder.CreateFileAsync("vs.exe", Windows.Storage.CreationCollisionOption.ReplaceExisting);
                using (MemoryStream stream = await downloader.DownloadFileTaskAsync(mylink) as MemoryStream)
                    await Windows.Storage.FileIO.WriteBytesAsync(sampleFile, stream.ToArray());
```

Corrected your sample repository:
[Downloader UWP.zip](https://github.com/bezzad/Downloader/files/9439575/Downloader.UWP.zip)
