### ISSUE TITLE
The calling thread cannot access this object because another thread owns it

### ISSUE THREAD

**Issue by 593172440** [bezzad/Downloader#143]
In .net framework 4.8 WPF
I New Create UserControl Name "Loading" And apply it Downloader . In another xaml Grid.Children.Add(Loading).Unable to close after download is complete.
prompt:
System.InvalidOperationException:“The calling thread cannot access this object because another thread owns it。”
Ask how to end this object in the loading interface

**Comment by bezzad** [comment]
When using WPF or another UI framework, it is not possible to directly access the main thread (UI thread) from another thread. Once your downloads are complete and you resume the await task with the result, the current thread may not be the main thread due to the Downloader running scenarios. Therefore, to call UI elements like Grid, you must use the Dispatcher, as shown in the code below:

```csharp
Grid.Dispatcher.Invoke(new Action(() => Grid.Children.Add(Loading)));
```

This is a .Net thread management control. For more information, please refer to the following link:

https://learn.microsoft.com/en-us/dotnet/desktop/wpf/advanced/threading-model?redirectedfrom=MSDN&view=netframeworkdesktop-4.8
