### ISSUE TITLE
Chunk displaying no progress yet still downloads.

### ISSUE THREAD

**Issue by ulnk** [bezzad/Downloader#145]
This is the exact copy of the example app but with a 40GB Zip. Is there a way to make sure it properly works?
Okay as I am writing this it has now gone past 100%!
![image](https://github.com/bezzad/Downloader/assets/93608862/b6ef5219-8ae7-4d75-bff0-97f88efbf984)

![image](https://github.com/bezzad/Downloader/assets/93608862/a65eae07-e543-41ee-8133-072123bb140d)
![image](https://github.com/bezzad/Downloader/assets/93608862/d60f7b8e-7cf7-4f9e-a23e-3c7f2b827759)

**Comment by bezzad** [comment]
If you encounter any problems with the user interface of the sample project, we suggest building your own app. This is because the sample project relies on third-party libraries that may not display progress correctly on certain command-line interfaces.

Rest assured that we have comprehensive unit tests for all the Downloader commands, ensuring that they have a high coverage rate.
