### ISSUE TITLE
Download error in sample application

### ISSUE THREAD

**Issue by AHpxChina** [bezzad/Downloader#19]
System.IO.InvalidDataException: 'File size is invalid!'
it's the first time I run the app and change no code

**Comment by AHpxChina** [comment]
update: it can be download correctly in a single file, but it has **System.IO.InvalidDataException: 'File size is invalid!'** a  occurred when a multi-file download

**Comment by bezzad** [comment]
This exception occurred When the file size less than zero. So this file size is less than or equal to zero when the server returns this value or does not support the request submission method!
Now an issue has been found in the `GetFileSize` method that takes all the web exceptions and returns the size value to -1 to catch this exception and throw new `InvalidDataException`. But in the next version, I changed this method so that only exceptions such as "Request method not supported" (for Http response status 403 or 405) will be taken and the rest of the exceptions will be transferred to higher levels.
Please download and run the new version (1.9.4) of this package. This time the main exception will occur, which has been caught to mistaken in older versions so far. Please send it to me.

Thank you very much for your help.

**Comment by AHpxChina** [comment]
thanks! it works!
shall I close this issue?

**Comment by bezzad** [comment]
This is probably a problem with the server-side or the Internet. But if there is a problem again, the main error will be displayed for you.
Thanks for following up
