### ISSUE TITLE
Allow Pausing downloads

### ISSUE THREAD

**Issue by goaaats** [bezzad/Downloader#20]
Please add a method to DownloadService to allow for pausing the active downloads.

This is useful for example when downloading big files and trying to offer a "Pause" feature for users, in case they need to use their bandwidth for something else.

**Comment by bezzad** [comment]
Dear friend, this feature already exists and you should use it as follows.
The ‍`DownloadService` class has a value called `Package` that stores each step of the download. You must call the `CancelAsync` method to stop or pause the download, and if you continue again, you must call the same DownloadFileAsync function with the Package parameter to continue your download! For example:

### Start Download and keep package file:

```csharp
var file = @"Your_Path\fileName.zip";
var url = @"https://file-examples.com/fileName.zip";
var pack = downloader.Package;
await downloader.DownloadFileAsync(url, file);
```

### Stop or Pause Download:

```csharp
downloader.CancelAsync(); 
```

### Resume Download:

```csharp
await downloader.DownloadFileAsync(pack); 
```

If this process is difficult for you, tell me to add Pause and Resume functions for you.

**Comment by bezzad** [comment]
This method is so that you can even save your large downloads with a very small amount in the `Package` and after restarting the program, restore it again and start continuing your download. In fact, the packages are your instant download snapshots. If your download config has `OnTheFlyDownload`, the downloaded bytes ​​will be stored in the package itself, but otherwise, only the address of the downloaded files will be included and you can resume it whenever you like.

**Comment by goaaats** [comment]
I wasn't aware of this - thank you very much!
