### ISSUE TITLE
Big download stalls after a while

### ISSUE THREAD

**Issue by goaaats** [bezzad/Downloader#55]
Hello, I'm embedding this library in my app and after updating to 2.2.8, certain big downloads seem to stall after a while.

Here is my configuration object:
```
			ParallelDownload = true, // download parts of file as parallel or not
            BufferBlockSize = 8000, // usually, hosts support max to 8000 bytes
            ChunkCount = 8, // file parts to download
            MaxTryAgainOnFailover = int.MaxValue, // the maximum number of times to fail.
            OnTheFlyDownload = false, // caching in-memory mode
            Timeout = 10000, // timeout (millisecond) per stream block reader
            TempDirectory = Path.GetTempPath(), // this is the library default
            RequestConfiguration = new RequestConfiguration
            {
                UserAgent = "FFXIV PATCH CLIENT",
                Accept = "*/*"
            },
            MaximumBytesPerSecond = App.Settings.SpeedLimitBytes / MAX_DOWNLOADS_AT_ONCE
```
In this example, `MaximumBytesPerSecond` is confirmed to be set to 0 on initialization and as such will be its maximum value.

I currently run 4 downloads at once. After a while, all 4 will get stuck. The `BytesPerSecondSpeed` on `DownloadProgressChanged` will end up at some value between 100-200kbps, and will not receive any further updates. Progress will not advance.

Is this a problem with my usage of the library? You can see the whole logic for downloading files here: https://github.com/goatcorp/FFXIVQuickLauncher/blob/master/XIVLauncher/Game/Patch/PatchManager.cs#L146

When downloads get stuck, even after the specified timeout, the error/cancelled objects are null.
I've ruled out the download server, as I can perform more than 4 simultaneous downloads using JDownloader just fine.
Disk space is not an issue.

Let me know if I can help you any further reproducing this.

#### Sample files:
http://patch-dl.ffxiv.com/game/4e9a232b/H2017.06.06.0000.0001a.patch
http://patch-dl.ffxiv.com/game/4e9a232b/H2017.06.06.0000.0001b.patch
http://patch-dl.ffxiv.com/game/4e9a232b/H2017.06.06.0000.0001c.patch
http://patch-dl.ffxiv.com/game/4e9a232b/H2017.06.06.0000.0001d.patch
[...]
http://patch-dl.ffxiv.com/game/4e9a232b/H2017.06.06.0000.0001m.patch

**Comment by bezzad** [comment]
Hi @goaaats, I have a few questions for you:

1. Does this problem occur when you set the value of `MaximumBytesPerSecond` equal to `int.MaxValue`?

2. When you have only one download without syncing with other downloads, is there still this problem?

3. Please remove any `ServicePointManager.DefaultConnectionLimit` setter codes from your apps and test again. Does solve this problem? ([For example](https://github.com/goatcorp/FFXIVQuickLauncher/blob/master/XIVLauncher/Game/Patch/PatchManager.cs#L101))

4. One time to test this issue, Please pass the `null` parameter for DownloadOption of DownloadService constructor and run again with this scenario. Does solve it?

**Comment by goaaats** [comment]
Thanks for your quick answer!

> Does this problem occur when you set the value of MaximumBytesPerSecond equal to int.MaxValue?

This doesn't seem to make any difference, the setter was already setting it to int.MaxValue though.

<br>

> When you have only one download without syncing with other downloads, is there still this problem?

No, when only running one download at a time, the problem doesn't seem to occur.

<br>

> Please remove any ServicePointManager.DefaultConnectionLimit setter codes from your apps and test again. Does solve this problem? (For example)

Removing the ``ServicePointManager.DefaultConnectionLimit = 255;`` seems to cause the issue later than before, however, this might just be a coincidence - I tried twice (using my own download options).

<br>

> One time to test this issue, Please pass the null parameter for DownloadOption of DownloadService constructor and run again with this scenario. Does solve it?

This causes the download rate to be quite a bit slower than before, naturally - on my 50mbit/s connection, I now only get about 4mb/s instead of 7mb/s, but it does seem to solve the problem.

Do you think this might be related to the amount of open connections? As I said, other download managers seem to be able to download these files consistently at high speeds.

**Comment by bezzad** [comment]
[0]:https://github.com/goatcorp/FFXIVQuickLauncher/blob/3f4168bc1e91c3e71c62bdfcba406a63e26c5819/XIVLauncher/Game/Patch/PatchManager.cs#L261

[1]:https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.run?view=net-5.0

I checked your project codes and I see you create the `DownloadService` object and call the `DownloadFileTaskAsync` method's from the same place with the name of `DownloadPatchAsync` which is return a `Task` and must be `awaited` from the upper caller. But you call it from [this line][0] and without await on Task. So I think your long processes (`DownloadPatchAsync`) may be ignored from OS or have some exception at execution that can't be thrown to the caller method.

I suggest you do not use the [Task.Run(action)][1] method to call a task because the called method itself is already a `Task` type. And every long task needs a reference to know where to turn back. When you do not `await` a `Task`, it's like to fire and forget a method. Something like calling a method of the return type of `async void`.
And better to await on any tasks you want to call it.
