### ISSUE TITLE
long url can not be downloaded

### ISSUE THREAD

**Issue by ghost1372** [bezzad/Downloader#57]
The following link cannot be downloaded I tested with and without VPN and it does not work

`https://subf2m.co/subtitles/farsi_persian-text/x3cqTn4LAYuJK5RKSaSYnXewfSU6iVUgSYDkn9DehSsFVXf1R4u5miZZ6v7w6nRZrSkeo1pneD_1Dj7srraAtYr12bchHoiHZEBrJqc1aq-k9fa0rQPJuCL_FKHppoqL0?name=UmljayBhbmQgTW9ydHkgRmlmdGggU2Vhc29uIFBlcnNpYW4gc3VidGl0bGUgLSBTdWJmMm0gW3N1YmYybS5jb10uemlw`

Internet Download Manager downloads without any problems

**Comment by bezzad** [comment]
The problem of not downloading this address has nothing to do with its length of URL and the downloader can download from any address. 
The problem is with the size of the file, which does not provide from the file header. I am investigating this problem and hope it will be resolved soon.
Thanks for reporting this problem.
