### ISSUE TITLE
Download progress not tracked for small file sizes

### ISSUE THREAD

**Issue by haysacks** [bezzad/Downloader#84]
Hi, I've been using your library for a download manager, and it's working really well, but the event handler DownloadProgressChangedEventArgs does not seem to detect progress changes for downloads of small files (like around 5 MB). The progress is stuck at 0% even after completion of the download.

**Comment by bezzad** [comment]
@haysacks Hi, We have never seen such a problem even for files up to kilobytes. There may be a problem with your download address. Because in some cases, the file server does not put the file size information in the response header, and in this case, the download is done without progress until the received byte value is zero. This is a server issue and nothing can be done about it.
For sure the issue is the same as my above description, please attach your download link to test it.

**Comment by bezzad** [comment]
I checked your URL and no `Content-Length` in the response header:
![image](https://user-images.githubusercontent.com/10928710/162560292-cc6c74a3-7031-4dc1-8f88-dd278d8321b5.png)
