### ISSUE TITLE
Error during download

### ISSUE THREAD

**Issue by babakmdi** [bezzad/Downloader#93]
Hi
Sometimes I get this error for large files.
the file is 1.4 GB, it was downloaded to 89 MB and gave this error
Message = "The SSL connection could not be established, see inner exception."

my link : https://5f8u2z8mn5qjqvfdxs59z5g6aw8djtnew.kinguploadf2m15.xyz/Film/2022/Minions.The.Rise.of.Gru.2022.1080p.WEB-DL.GalaxyRG.Farsi.Sub.Film2Media.mkv

**Comment by babakmdi** [comment]
Hello,

**Comment by bezzad** [comment]
Hi, Please send me the inner exception message and type

**Comment by babakmdi** [comment]
![image](https://user-images.githubusercontent.com/65450661/184493309-5bfc14d0-17cf-4a05-bc30-19ccb532b2b2.png)
![image](https://user-images.githubusercontent.com/65450661/184493322-e5b18602-1cdc-4ee2-8d1b-a95b929c7a3c.png)

**Comment by babakmdi** [comment]
Hello, How Are you Sir? 
Any News About This Problem ?

**Comment by bezzad** [comment]
Your inner exception message was: `The remote certificate is invalid because of errors in the certificate chain: NotTimeValid`

It happens when your connection SSL certificate is expired. Therefore, this issue only happens in special situations that I don't know why. I tested your URL and found out the Downloader caught this exception when it was creating 3rd chunk. I think the server doesn't let it happens. 

To solve this problem, I added a certificate validation callback method to the Downloader to ignore this issue when the type of error is `NotTimeValid`. In the next version of the Downloader, this issue will be fixed.

**Comment by babakmdi** [comment]
Ok, Thanks to you

**Comment by bezzad** [comment]
The new version released and you can test it. If you have any issues with the new version, take sure to tell me.

**Comment by babakmdi** [comment]
Hello , Thanks to you.
should i changes my code? or not?

**Comment by bezzad** [comment]
No, you don't need to change your codes, just update the Downloader package to the last version.
