### ISSUE TITLE
Download small files without chunk is faster

### ISSUE THREAD

**Issue by luomo-pro** [bezzad/Downloader#95]
I test downloading very small files, for example 3KB files, setting ChunkCount to 1 will be faster than setting it to 16.
I think it should be enough to use single thread to download very small files, multi-threading will slow down the speed instead.
Is it possible to add a property to disable chunk downloading when the file is smaller than a certain size?
Thank you very much!

**Comment by bezzad** [comment]
Hi @luomo-pro 
Your idea is so good. But we haven't any option for this feature now. I will add this request to my future box to do it as soon as possible.
Thanks a lot

**Comment by bezzad** [comment]
@luomo-pro  new version (3.0.0-beta) release and you can see the new feature on this version, now.
If the feature you requested was completed in this version, please let us know so that the final version can be published.
The changes in this version are fundamental and that is why this version is beta.

**Comment by luomo-pro** [comment]
hi,@bezzad
I tested the latest version and this is the feature I wanted, very good, thank you!
